import type { MediaItem, Setlist } from '../types';

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  { id: 1001, title: 'Sample Feature Film A', type: 'Film', duration: 135, status: 'Synced', targetLocations: 25, expiryDate: '2026-12-31', posterPath: 'https://placehold.co/300x450/0E7B35/FAEF06?text=JEMIMA', genre: 'History, Romance, Drama', ageRating: '13+', audioType: 'Dolby Atmos', publisher: 'Studio Alpha', director: 'Director A', volume: 80, synopsis: 'A romantic historical drama following the lives of characters during a pivotal moment in history.' },
  { id: 1, title: 'Short Film Demo', type: 'Film', duration: 119, status: 'Synced', targetLocations: 12, expiryDate: '2026-12-31', posterPath: null, genre: 'Comedy, Horror', ageRating: '13+', audioType: '5.1 Surround', publisher: 'Studio Bravo', director: 'Director B', volume: 80, synopsis: 'A group of friends navigate a series of comedic and spooky misadventures.' },
  { id: 2, title: 'Indie Drama Showcase', type: 'Film', duration: 121, status: 'Expiring Soon', targetLocations: 14, expiryDate: '2026-05-10', posterPath: null, genre: 'Drama', ageRating: '17+', audioType: '5.1 Surround', publisher: 'Studio Charlie', director: 'Director C', volume: 85, synopsis: 'An intimate look at the struggles and triumphs of independent artists.' },
  { id: 3, title: 'Promo Bumper 30s', type: 'Bumper', duration: 0.5, status: 'Not Synced', targetLocations: 14, expiryDate: '2099-12-31', posterPath: null, genre: 'Bumper', ageRating: 'SU', audioType: 'Stereo', publisher: 'JEMIMA Creative', director: 'Creative Dept', volume: 90, synopsis: 'Short promotional bumper for venue branding.' },
  { id: 4, title: 'Documentary Preview', type: 'Film', duration: 100, status: 'Synced', targetLocations: 10, expiryDate: '2026-08-01', posterPath: null, genre: 'Documentary', ageRating: '17+', audioType: '5.1 Surround', publisher: 'Studio Delta', director: 'Director D', volume: 75, synopsis: 'A preview of an upcoming documentary series exploring nature and culture.' },
  { id: 5, title: 'Local Coffee Ad', type: 'Advertisement', duration: 0.5, status: 'Expired', targetLocations: 2, expiryDate: '2026-04-01', posterPath: null, genre: 'Ad', ageRating: 'SU', audioType: 'Stereo', publisher: 'Local Co', director: 'Director E', volume: 100, synopsis: 'A short advertisement for a local coffee brand.' },
  { id: 6, title: 'Action Blockbuster B', type: 'Film', duration: 119, status: 'Processing', targetLocations: 0, expiryDate: '2026-10-01', posterPath: null, genre: 'Action', ageRating: '17+', audioType: 'Dolby Atmos', publisher: 'Studio Echo', director: 'Director F', volume: 82, synopsis: 'A high-octane action film with stunning visual effects.' },
  { id: 7, title: 'Horror Anthology Entry', type: 'Film', duration: 122, status: 'Synced', targetLocations: 14, expiryDate: '2026-11-01', posterPath: null, genre: 'Horror', ageRating: '17+', audioType: '5.1 Surround', publisher: 'Studio Foxtrot', director: 'Director G', volume: 80, synopsis: 'A chilling entry in a horror anthology series.' },
  { id: 8, title: 'Family Adventure Film', type: 'Film', duration: 98, status: 'Expiring Soon', targetLocations: 5, expiryDate: '2026-05-15', posterPath: null, genre: 'Adventure', ageRating: 'PG', audioType: '5.1 Surround', publisher: 'Studio Golf', director: 'Director H', volume: 85, synopsis: 'A fun-filled adventure for the whole family.' },
  { id: 9, title: 'Thriller Sequel', type: 'Film', duration: 138, status: 'Synced', targetLocations: 8, expiryDate: '2027-01-01', posterPath: null, genre: 'Thriller', ageRating: '17+', audioType: 'Dolby Atmos', publisher: 'Studio Hotel', director: 'Director I', volume: 80, synopsis: 'The gripping sequel to a critically acclaimed thriller.' },
  { id: 10, title: 'Drama Feature C', type: 'Film', duration: 110, status: 'Synced', targetLocations: 4, expiryDate: '2026-09-01', posterPath: null, genre: 'Drama', ageRating: 'PG-13', audioType: '5.1 Surround', publisher: 'Studio India', director: 'Director J', volume: 78, synopsis: 'A character-driven drama exploring themes of resilience.' },
];

export const MOCK_SETLISTS: Setlist[] = [
  {
    id: 1,
    name: 'Monday Standard Mix',
    items: 4,
    duration: 124,
    updated: '2026-05-07 10:24:45',
    status: 'Active',
    locations: 12,
    date: '2026-10-12',
    log: 'System Admin updated advertisement sequence.',
  },
  {
    id: 2,
    name: 'Tuesday Lineup',
    items: 4,
    duration: 124,
    updated: '2026-05-06 14:12:05',
    status: 'Active',
    locations: 12,
    date: '2026-10-13',
    log: 'Automated daily generation.',
  },
  {
    id: 3,
    name: 'Midweek Special',
    items: 5,
    duration: 140,
    updated: '2026-05-05 09:30:12',
    status: 'Draft',
    locations: 8,
    date: '2026-10-14',
    log: "User 'Admin' added new bumper.",
  },
  {
    id: 4,
    name: 'Weekend Blockbuster Mix',
    items: 6,
    duration: 180,
    updated: '2026-05-01 16:45:00',
    status: 'Active',
    locations: 14,
    date: '2026-10-15',
    log: 'HQ approved weekend schedule.',
  },
  {
    id: 5,
    name: 'Evening Showcase',
    items: 5,
    duration: 160,
    updated: '2026-04-20 22:15:30',
    status: 'Active',
    locations: 14,
    date: '2026-10-16',
    log: 'Studio Manager approved sequence.',
  },
];
